version: '3'

services:
  node1:
    build: .
    container_name: node1
    environment:
      - FLASK_ENV=development
      - PEERS=http://node2:5000,http://node3:5000
    ports:
      - "5000:5000"
    command: ["python", "run_node.py"]

  node2:
    build: .
    container_name: node2
    environment:
      - FLASK_ENV=development
      - PEERS=http://node1:5000,http://node3:5000
    ports:
      - "5001:5000"
    command: ["python", "run_node.py"]

  node3:
    build: .
    container_name: node3
    environment:
      - FLASK_ENV=development
      - PEERS=http://node1:5000,http://node2:5000
    ports:
      - "5002:5000"
    command: ["python", "run_node.py"]
